services:

  app:
    container_name: myweb-project
    build:
      context: .
      dockerfile: ./Dockerfile
    image: web-project
    restart: always
    tty: true
    env_file:
      - .env.production
    ports:
      - 8080:8080
    networks:
      - fastapi_network

networks:
  fastapi_network:
    external: true